#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "shields"
name = "Shields"
description.en = "Concise, consistent, and legible badges in SVG and raster format"
description.fr = "Badges concis, cohérents et lisibles au format SVG et raster"

version = "2024-11-02~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "CC0-1.0"
website = "https://shields.io/"
admindoc = "https://shields.io/docs"
code = "https://github.com/badges/shields"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false

disk = "512M"
ram.build = "1G"
ram.runtime = "512M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]

    url = "https://github.com/badges/shields/archive/refs/tags/server-2024-11-02.tar.gz"
    sha256 = "b6719f5587d4ee3158a6798c576fe1d43ef2c4aba67523e4f2df16e5cdb0bd61"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
